
try{
    console.log(a)
}
catch(e)
{
    console.log("error")
}